# Generated by Django 4.0.5 on 2022-07-26 09:06

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_remove_registeredusers_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='firstname',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='lastname',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='post',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
